### ISSUE TITLE
CantHurtMe page becomes unusable after opening Menu

### ISSUE THREAD

**Issue by yilverdeja** [ABHIGYAN-MOHANTA/UnbreakableMe#1]
The phone I used to test this app was a One Plus 6, with Android 11, running the Oxygen OS 11.1.2.2 .

Wasn't able to test the other features aside from the Taking Inventory. When I open the hamburger menu, I can't collapse it anymore. I can click on the different menu items and they go to their respective pages, but I can't interact with the page due to the opened menu.

![Screenshot_20230819-150808.jpg](https://github.com/ABHIGYAN-MOHANTA/UnbreakableMe/assets/29952939/535c086c-860f-40a7-8fc2-f983f90a3665)

**Comment by ABHIGYAN-MOHANTA** [comment]
Try once again after clearing cache and maybe storage too! I think since it's the Android internal build(.apk file), it has some optimisation issues! The actual build(.aab file) will be good I think! I am personally testing on redmi 7a which has 2gb ram, and a Samsung both with android 13! A few of my friends have tested it too! Thanks for reporting the issue! Let me know, if this issue still persists! I will into android 11 compatibility, if there is some error on my side. Thanks again!

**Comment by yilverdeja** [comment]
Not sure what happened, but I tried to reproduce the bug on my phone and it works now. I'll try to reinstall the app later and see if this but appears again

**Comment by ABHIGYAN-MOHANTA** [comment]
Thank you! Glad, it works now! Maybe it needs some time in the initial install, I have an idea, why that might be happening! Thanks for reporting the issue though! Have a great day ahead!

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey, in the latest release, I have fixed some dependency issues! I think the error you were facing at first was due to incompatible version numbers of different dependencies! Give the latest version a try! I think you will like it!

**Comment by yilverdeja** [comment]
Just tried it right now - I still think the hamburger menu is very buggy and really ruins the user experience. I can hardly go and test any of the pages in the `CantHurtMe` tab.

Personally, I think there are just too many navigation items. However, if you want to keep all those menu items in the hamburger menu, perhaps you can try closing the menu if the user clicks a selected menu item:

As an example, if I open the menu and click on "Taking Souls", the menu is updated and is now selecting the "Taking Souls" item. However, if the user clicks again on "Taking Souls", then the menu should close.

**Comment by ABHIGYAN-MOHANTA** [comment]
Thanks again man, I recently faced the same issue, although it worked after clearing cache and storage and rebooting my device. But it shouldn't be like that! The hamburger menu should close automatically, but sometimes it misbehaves! Honestly, speaking this is not an issue from my side, but from expo! I thinking of migrating the entire app to bare react native! However, just want to give the production build a try, once. All this time I have been testing in the developer preview build, I hope the production build is good from expo! Created my play store account, yesterday. It will take some days to verify my identity! If everything goes well, the the app will be fast and launched to play store within a week. The production build is 20 MB in size, whereas the developer preview build is 50 MB! I have high hopes for it! Thanks again for your time and feedback! Just clear cache and storage for now! And uninstall it! I will send you the production build on play store, once its ready! Thanks again!

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey, I got a good idea! I completely replaced the side bar, with top nav bar, now it shouldn't lag or crash! Checkout the latest release! You can uninstall the play store version if you like!
